import PDFDocument from "pdfkit";

export const generateSkillGapReport = async (skillGapAnalysis, userInfo, analysisData = {}) => {
   const doc = new PDFDocument({
      margins: { top: 50, bottom: 80, left: 50, right: 50 },
      size: 'A4',
      info: {
         Title: 'Career Intelligence & Skill Gap Analysis',
         Author: 'AI Resume Analyzer',
         Subject: 'Career Development Report',
      }
   });

   const buffers = [];
   doc.on('data', buffers.push.bind(buffers));

   // --- COLOR PALETTE ---
   const colors = {
      primary: '#0F172A',
      secondary: '#2563EB',
      accent: '#4F46E5',
      textMain: '#334155',
      textLight: '#64748B',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      bgLight: '#F8FAFC',
      line: '#E2E8F0',
   };

   // --- Use the calculated score (matches frontend) or fall back to AI's raw score ---
   const calculatedScore = analysisData?.calculatedScore;
   const overallTotalScore = typeof calculatedScore === 'object'
      ? calculatedScore.totalScore
      : (typeof calculatedScore === 'number' ? calculatedScore : skillGapAnalysis?.jobReadinessScore || 0);

   // Use the explicitly stored targetJobRole, or fall back to skillGapAnalysis
   const targetJobRole = analysisData?.targetJobRole || skillGapAnalysis?.targetJobRole || 'Not Specified';

   // AI Feedback data (for additional sections in the PDF)
   const aiFeedback = analysisData?.aiFeedback;

   // --- PAGE SETUP ---
   let pageNumber = 1;

   const drawPageChrome = () => {
      // Top color bar
      doc.rect(0, 0, 595, 10).fill(colors.primary);
      // Footer
      const bottomY = doc.page.height - 50;
      doc.moveTo(50, bottomY).lineTo(545, bottomY).lineWidth(1).strokeColor(colors.line).stroke();
      doc.font('Helvetica').fontSize(9).fillColor(colors.textLight)
         .text('Generated by AI Resume Analyzer', 50, bottomY + 15, { lineBreak: false });
      doc.text(`Page ${pageNumber}`, 500, bottomY + 15, { lineBreak: false });
   };

   doc.on('pageAdded', () => {
      pageNumber++;
      drawPageChrome();
      doc.x = 50; // Reset x to left margin (drawPageChrome sets it to 500)
      doc.y = 40;
   });

   // First page chrome
   drawPageChrome();
   doc.x = 50; // Reset x to left margin (drawPageChrome sets it to 500)

   // --- TITLE ---
   doc.y = 40;
   doc.moveDown(1);
   doc.font('Helvetica-Bold').fontSize(24).fillColor(colors.primary).text('CAREER INTELLIGENCE', { align: 'center' });
   doc.font('Helvetica').fontSize(13).fillColor(colors.textLight).text('SKILL GAP & READINESS REPORT', { align: 'center' });
   doc.moveDown(1.5);

   // --- CANDIDATE INFO BOX ---
   const infoBoxY = doc.y;
   doc.roundedRect(50, infoBoxY, 495, 85, 8).fill(colors.bgLight).strokeColor(colors.line).lineWidth(1).stroke();

   doc.font('Helvetica-Bold').fontSize(10).fillColor(colors.textLight).text('PREPARED FOR', 70, infoBoxY + 15);
   doc.font('Helvetica-Bold').fontSize(16).fillColor(colors.primary).text(userInfo?.name?.toUpperCase() || 'CANDIDATE', 70, infoBoxY + 30);

   doc.font('Helvetica-Bold').fontSize(10).fillColor(colors.textLight).text('TARGET JOB ROLE', 300, infoBoxY + 15);
   doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.secondary).text(targetJobRole, 300, infoBoxY + 30, { width: 220 });

   const reportDate = userInfo?.analysisDate ? new Date(userInfo.analysisDate).toLocaleDateString() : new Date().toLocaleDateString();
   doc.font('Helvetica').fontSize(9).fillColor(colors.textLight).text(`Report Date: ${reportDate}`, 70, infoBoxY + 60);

   doc.y = infoBoxY + 105;
   doc.x = 50; // Reset X to margin

   // --- OVERALL SCORE ---
   const score = overallTotalScore;
   doc.font('Helvetica-Bold').fontSize(15).fillColor(colors.primary).text('OVERALL READINESS SCORE');
   doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
   doc.y += 15;

   const scoreY = doc.y;
   let scoreColor = colors.danger;
   let statusText = 'Needs Improvement';
   if (score >= 75) { scoreColor = colors.success; statusText = 'Excellent Fit'; }
   else if (score >= 50) { scoreColor = colors.warning; statusText = 'Moderate Fit'; }

   // Score circle
   doc.circle(95, scoreY + 35, 35).fill('#FFFFFF').strokeColor(colors.line).lineWidth(5).stroke();
   doc.circle(95, scoreY + 35, 35).strokeColor(scoreColor).lineWidth(5).stroke();
   doc.font('Helvetica-Bold').fontSize(22).fillColor(scoreColor).text(`${score}`, 65, scoreY + 26, { width: 60, align: 'center' });

   doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text(statusText, 155, scoreY + 15);
   doc.font('Helvetica').fontSize(10).fillColor(colors.textMain).text(
      `Based on weighted analysis of your resume against industry requirements for the ${targetJobRole} role.`,
      155, scoreY + 35, { width: 360, lineGap: 3 }
   );

   doc.y = scoreY + 90;
   doc.x = 50;

   // --- SCORE BREAKDOWN (from calculated score) ---
   if (typeof calculatedScore === 'object' && calculatedScore) {
      doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text('SCORE BREAKDOWN');
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
      doc.y += 15;

      const scoreItems = [
         { label: 'Skills Match', value: calculatedScore.skillsMatch || 0, weight: '30%' },
         { label: 'Experience', value: calculatedScore.experience || 0, weight: '20%' },
         { label: 'Projects', value: calculatedScore.projects || 0, weight: '15%' },
         { label: 'Keywords', value: calculatedScore.keywords || 0, weight: '15%' },
         { label: 'Formatting', value: calculatedScore.formatting || 0, weight: '10%' },
         { label: 'Impact Words', value: calculatedScore.impactWords || 0, weight: '10%' },
      ];

      const barStartX = 170;
      const barWidth = 280;

      scoreItems.forEach(item => {
         const rowY = doc.y;
         doc.font('Helvetica-Bold').fontSize(9).fillColor(colors.textMain).text(`${item.label} (${item.weight})`, 55, rowY + 3);
         // Background bar
         doc.roundedRect(barStartX, rowY, barWidth, 14, 3).fill('#E2E8F0');
         // Value bar
         const fillWidth = Math.max(2, (item.value / 100) * barWidth);
         let barColor = colors.danger;
         if (item.value >= 70) barColor = colors.success;
         else if (item.value >= 40) barColor = colors.warning;
         doc.roundedRect(barStartX, rowY, fillWidth, 14, 3).fill(barColor);
         // Score text
         doc.font('Helvetica-Bold').fontSize(9).fillColor(colors.textMain).text(`${item.value}%`, barStartX + barWidth + 10, rowY + 3);
         doc.y = rowY + 22;
      });

      doc.y += 10;
   }

   // --- EXECUTIVE SUMMARY ---
   const present = skillGapAnalysis?.skillMatches?.filter(s => s.status === 'present')?.length || 0;
   const partial = skillGapAnalysis?.skillMatches?.filter(s => s.status === 'partial')?.length || 0;
   const missing = skillGapAnalysis?.missingSkills?.length || 0;
   const total = present + partial + missing;

   doc.x = 50;
   doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text('EXECUTIVE SUMMARY');
   doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
   doc.y += 15;

   const statsY = doc.y;
   const statBoxWidth = 155;

   const drawStatBox = (x, title, value, color) => {
      doc.roundedRect(x, statsY, statBoxWidth, 60, 6).fill(colors.bgLight).strokeColor(colors.line).lineWidth(1).stroke();
      doc.font('Helvetica-Bold').fontSize(24).fillColor(color).text(value.toString(), x, statsY + 12, { width: statBoxWidth, align: 'center' });
      doc.font('Helvetica-Bold').fontSize(8).fillColor(colors.textLight).text(title, x, statsY + 42, { width: statBoxWidth, align: 'center' });
   };

   drawStatBox(50, 'TOTAL SKILLS CHECKED', total, colors.primary);
   drawStatBox(220, 'MATCHING SKILLS', present, colors.success);
   drawStatBox(390, 'MISSING GAPS', missing, colors.danger);

   doc.y = statsY + 80;
   doc.x = 50;

   // --- DETAILED SKILL ANALYSIS TABLE ---
   if (skillGapAnalysis?.skillMatches && skillGapAnalysis.skillMatches.length > 0) {
      if (doc.y > 500) doc.addPage();
      doc.x = 50; // Reset after page add

      doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text('DETAILED SKILL ANALYSIS');
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
      doc.y += 15;

      const col1 = 50, col2 = 250, col3 = 390;

      const drawTableHeader = () => {
         const headerY = doc.y;
         doc.rect(50, headerY, 495, 26).fill(colors.primary);
         doc.font('Helvetica-Bold').fontSize(9).fillColor('#FFFFFF');
         doc.text('SKILL', col1 + 15, headerY + 8);
         doc.text('STATUS', col2 + 10, headerY + 8);
         doc.text('PROFICIENCY / CONTEXT', col3 + 10, headerY + 8);
         doc.y = headerY + 26;
      };

      drawTableHeader();

      skillGapAnalysis.skillMatches.forEach((item, i) => {
         if (doc.y > 700) {
            doc.addPage();
            drawTableHeader();
         }

         const rowY = doc.y;
         const rowColor = i % 2 === 0 ? colors.bgLight : '#FFFFFF';
         doc.rect(50, rowY, 495, 30).fill(rowColor);

         doc.font('Helvetica-Bold').fontSize(9).fillColor(colors.textMain).text(item.skill, col1 + 15, rowY + 10, { width: 175, height: 15, ellipsis: true });

         let statusColor = colors.danger;
         if (item.status === 'present') statusColor = colors.success;
         else if (item.status === 'partial') statusColor = colors.warning;

         doc.font('Helvetica-Bold').fontSize(9).fillColor(statusColor).text((item.status || '').toUpperCase(), col2 + 10, rowY + 10);
         doc.font('Helvetica').fontSize(9).fillColor(colors.textLight).text(item.industryStandard || 'Not specified', col3 + 10, rowY + 10, { width: 135, height: 15, ellipsis: true });

         doc.y = rowY + 30;
      });
   }

   // --- CRITICAL MISSING SKILLS ---
   if (skillGapAnalysis?.missingSkills && skillGapAnalysis.missingSkills.length > 0) {
      if (doc.y > 600) doc.addPage();
      doc.x = 50;
      doc.moveDown(1);

      doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text('CRITICAL SKILL GAPS');
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
      doc.y += 15;

      let currentX = 50;
      let currentY = doc.y;

      skillGapAnalysis.missingSkills.forEach(skill => {
         doc.font('Helvetica-Bold').fontSize(9);
         const textWidth = doc.widthOfString(skill) + 20;

         if (currentX + textWidth > 545) {
            currentX = 50;
            currentY += 30;
         }

         if (currentY > 700) {
            doc.addPage();
            currentY = doc.y;
            currentX = 50;
         }

         doc.roundedRect(currentX, currentY, textWidth, 22, 5).fill('#FEF2F2').strokeColor('#FECACA').lineWidth(1).stroke();
         doc.fillColor(colors.danger).text(skill, currentX + 10, currentY + 7);
         currentX += textWidth + 8;
      });
      doc.y = currentY + 40;
   }

   // --- AI FEEDBACK: STRENGTH AREAS ---
   const strengthAreas = aiFeedback?.strengthAreas || skillGapAnalysis?.strengthAreas || [];
   if (strengthAreas.length > 0) {
      if (doc.y > 600) doc.addPage();
      doc.moveDown(1);

      doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text('KEY STRENGTHS IDENTIFIED');
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
      doc.y += 15;

      strengthAreas.forEach((str, i) => {
         if (doc.y > 700) doc.addPage();
         doc.x = 50;
         const rowColor = i % 2 === 0 ? '#ECFDF5' : '#F0FDF4';
         const boxStart = doc.y;

         doc.roundedRect(50, boxStart, 495, 28, 4).fill(rowColor).stroke();
         doc.fillColor(colors.success).font('Helvetica-Bold').fontSize(10).text('>>', 65, boxStart + 9);
         doc.font('Helvetica-Bold').fontSize(10).fillColor(colors.success).text(str, 85, boxStart + 9, { width: 440 });

         doc.y = boxStart + 34;
      });
      doc.x = 50;
   }

   // --- IMPROVEMENT ROADMAP ---
   if (skillGapAnalysis?.improvementRoadmap && skillGapAnalysis.improvementRoadmap.length > 0) {
      doc.addPage();
      doc.x = 50;
      doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text('LEARNING ROADMAP');
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
      doc.y += 15;

      doc.font('Helvetica').fontSize(10).fillColor(colors.textMain).text('Targeted steps and curated resources to elevate your profile.', { lineGap: 4 });
      doc.y += 15;

      skillGapAnalysis.improvementRoadmap.forEach((item, i) => {
         if (doc.y > 620) doc.addPage();

         const boxY = doc.y;
         doc.roundedRect(50, boxY, 495, 90, 8).fill(colors.bgLight).strokeColor(colors.line).lineWidth(1).stroke();

         // Step number
         doc.circle(70, boxY + 22, 11).fill(colors.accent);
         doc.font('Helvetica-Bold').fontSize(11).fillColor('#FFFFFF').text(`${i + 1}`, 63, boxY + 17, { width: 14, align: 'center' });

         // Title & meta
         doc.font('Helvetica-Bold').fontSize(11).fillColor(colors.primary).text(item.skill || `Step ${i + 1}`, 90, boxY + 15, { width: 160 });

         let pColor = colors.accent;
         if (item.priority === 'high') pColor = colors.danger;
         else if (item.priority === 'medium') pColor = colors.warning;

         doc.font('Helvetica-Bold').fontSize(8).fillColor(pColor).text(`PRIORITY: ${(item.priority || 'normal').toUpperCase()}`, 90, boxY + 38, { width: 160 });
         doc.font('Helvetica').fontSize(9).fillColor(colors.textLight).text(`Timeline: ${item.timeline || 'TBD'}`, 90, boxY + 50, { width: 160 });

         // Resources divider
         doc.moveTo(265, boxY + 10).lineTo(265, boxY + 80).lineWidth(1).strokeColor(colors.line).stroke();

         // Resources
         doc.font('Helvetica-Bold').fontSize(9).fillColor(colors.textMain).text('RESOURCES:', 280, boxY + 15, { width: 200 });

         const resources = item.resources || [];
         resources.slice(0, 3).forEach((res, rIdx) => {
            doc.font('Helvetica').fontSize(8).fillColor(colors.secondary).text(`- ${res}`, 280, boxY + 32 + (rIdx * 14), { width: 250, height: 14, ellipsis: true });
         });

         doc.y = boxY + 105;
         doc.x = 50;
      });
   }

   // --- RECOMMENDATIONS ---
   const recommendations = skillGapAnalysis?.recommendations || [];
   if (recommendations.length > 0) {
      if (doc.y > 550) doc.addPage();
      doc.x = 50;
      doc.moveDown(1);

      doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text('ACTIONABLE INSIGHTS');
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
      doc.y += 15;

      recommendations.forEach((rec) => {
         if (doc.y > 670) doc.addPage();

         const textHeight = doc.heightOfString(rec, { width: 430, fontSize: 10 });
         const boxHeight = Math.max(35, textHeight + 16);
         const boxStart = doc.y;

         doc.roundedRect(50, boxStart, 495, boxHeight, 6).fill(colors.bgLight).strokeColor(colors.line).lineWidth(1).stroke();
         doc.font('Helvetica-Bold').fontSize(12).fillColor(colors.warning).text('*', 65, boxStart + 10);
         doc.font('Helvetica').fontSize(10).fillColor(colors.textMain).text(rec, 85, boxStart + 10, { width: 440, lineGap: 3 });

         doc.y = boxStart + boxHeight + 10;
      });
   }

   // --- AI FEEDBACK: KEYWORDS TO ADD ---
   if (aiFeedback?.keywordsToAdd && aiFeedback.keywordsToAdd.length > 0) {
      if (doc.y > 600) doc.addPage();
      doc.moveDown(1);

      doc.font('Helvetica-Bold').fontSize(14).fillColor(colors.primary).text('ATS KEYWORDS TO ADD');
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).lineWidth(1).strokeColor(colors.line).stroke();
      doc.y += 15;

      let kwX = 50;
      let kwY = doc.y;

      aiFeedback.keywordsToAdd.forEach(keyword => {
         doc.font('Helvetica-Bold').fontSize(9);
         const tw = doc.widthOfString(keyword) + 20;

         if (kwX + tw > 545) {
            kwX = 50;
            kwY += 28;
         }

         if (kwY > 700) {
            doc.addPage();
            kwY = doc.y;
            kwX = 50;
         }

         doc.roundedRect(kwX, kwY, tw, 22, 5).fill('#EEF2FF').strokeColor('#C7D2FE').lineWidth(1).stroke();
         doc.fillColor(colors.accent).text(keyword, kwX + 10, kwY + 7);
         kwX += tw + 8;
      });
      doc.y = kwY + 40;
   }

   // --- END OF REPORT ---
   doc.moveDown(3);
   doc.font('Helvetica-Bold').fontSize(9).fillColor(colors.line).text('★ ★ ★', { align: 'center', characterSpacing: 4 });
   doc.moveDown(0.5);
   doc.font('Helvetica').fontSize(8).fillColor(colors.textLight).text('End of Analysis Report', { align: 'center' });

   doc.end();

   return new Promise((resolve, reject) => {
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);
   });
};

// Original function for basic text (kept for backward compatibility)
export const generatePDFBuffer = async (textContent) => {
   return new Promise((resolve, reject) => {
      const doc = new PDFDocument();
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      doc.fontSize(12).text(textContent);
      doc.end();
   });
};

// New function for analysis summary
export const generateAnalysisSummary = async (analysisData) => {
   const doc = new PDFDocument();
   const buffers = [];
   doc.on('data', buffers.push.bind(buffers));

   doc.fontSize(18)
      .text('Resume Analysis Summary', { align: 'center' });

   doc.moveDown();

   if (analysisData.targetJobRole) {
      doc.fontSize(14)
         .text(`Target Role: ${analysisData.targetJobRole}`);
   }

   if (analysisData.overallScore !== undefined) {
      doc.text(`Overall Score: ${analysisData.overallScore}/10`);
   }

   doc.moveDown();

   if (analysisData.aiFeedback?.summary) {
      doc.fontSize(12)
         .text('AI Feedback Summary:')
         .moveDown(0.5)
         .text(analysisData.aiFeedback.summary, { align: 'justify' });
   }

   doc.end();

   return new Promise((resolve, reject) => {
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);
   });
};